SET SERVEROUTPUT ON;
DECLARE
nCount NUMBER;
BEGIN

SELECT count(*) into nCount FROM user_tables where table_name = 'DEPARTMENT';
IF(nCount > 0)
THEN
    DBMS_OUTPUT.PUT_LINE('DEPARTMENT TABLE ALREADY EXISTS');
ELSE
    EXECUTE IMMEDIATE  'CREATE TABLE DEPARTMENT(
    DEPT_ID NUMBER(10) PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL )';
END IF;

END;