--------------------------------------------------------
--  File created - Thursday-April-29-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure ADD_EVENT
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "ADMIN"."ADD_EVENT" (EV_NAME VARCHAR2, 
  EV_CAT IN VARCHAR2, EV_DATE IN DATE, EV_VENUE IN VARCHAR2, EV_LINK IN VARCHAR2 DEFAULT NULL)
AS 
E_CAT NUMBER(10);
E_VEN NUMBER(10);
M_ID NUMBER(10);
ERR NUMBER(10);
BEGIN

    SELECT MEMBER_ID INTO M_ID FROM MEMBERS WHERE UPPER(USERNAME) =UPPER((SELECT USER FROM DUAL));

    ERR:=1;
    SELECT CAT_ID INTO E_CAT FROM EVENT_CATEGORY WHERE UPPER(CAT_NAME)=UPPER(EV_CAT);

    ERR:=2;
    SELECT SITE_ID INTO E_VEN FROM EVENT_SITE WHERE UPPER(SITE_NAME)=UPPER(EV_VENUE);

    INSERT INTO EVENT (EVT_NAME, EVT_CAT_ID, EVT_DATETIME, EVT_HOST_ID,EVT_VENUE,EVT_LINK,EVT_STATUS)
    VALUES (EV_NAME, E_CAT, EV_DATE, M_ID,E_VEN, EV_LINK, 
    (SELECT EVT_STATUS_ID FROM EVENT_STATUS WHERE UPPER(EVT_STATUS)=UPPER('Registration Open')));
    COMMIT;
EXCEPTION
WHEN NO_DATA_FOUND THEN
    IF ERR=1 THEN
        DBMS_OUTPUT.PUT_LINE('INVALID EVENT CATEGORY');
    ELSIF ERR=2 THEN
        DBMS_OUTPUT.PUT_LINE('INVALID EVENT SITE');
    ELSE
      DBMS_OUTPUT.PUT_LINE('INVALID VALUE ENTERED, TRY AGAIN');
    END IF;
END ADD_EVENT;


/

  GRANT EXECUTE ON "ADMIN"."ADD_EVENT" TO "DB_MEMBERS";
