
CREATE OR REPLACE VIEW ALL_STUDENTS AS
SELECT M.FIRST_NAME|| ' ' ||M.LAST_NAME "STUDENT NAME",S.EMAIL ,U.UNI_NAME "UNIVERSITY NAME",D.DEG_NAME "DEGREE NAME",C.MAJ_NAME"MAJOR",S.STUDENT_BACKROUND "STUDENT BACKGROUND",S.EXPECTED_GRADDATE"EXPECTED GRADUATE DATE" 
FROM STUDENT S JOIN MEMBERS M
ON M.MEMBER_ID = S.MEMBER_ID
JOIN COURSE_MAJOR C
ON  C.MAJ_ID=S.MAJ_ID
JOIN DEGREE_LEVEL D
ON  S.DEGREE_LEVEL= DEG_ID
JOIN UNIVERSITY U
ON S.UNI_ID = U.UNI_id;
SELECT * FROM ALL_STUDENTS

CREATE OR REPLACE VIEW ALL_PROFESSORS AS
SELECT M.FIRST_NAME|| ' ' || M.LAST_NAME "PROFESSOR NAME",PU.EMAIL,U.UNI_NAME "UNIVERSITY NAME",P.PROF_BACKGROUND "PROFESSOR BACKGROUND",O.PROJ_NAME "PROJECT NAME",P.PROF_HIGHEST_QUAL "PROFESSOR HIGHEST QUALIFICATION"
FROM PROF_UNIVERSITY PU JOIN MEMBERS M
ON M.MEMBER_ID = PU.PROF_ID
JOIN PROFESSOR P
ON  P.MEMBER_ID=M.MEMBER_ID
JOIN OPEN_SOURCE_PROJECTS O
ON  O.PROF_ID= M.MEMBER_ID
JOIN UNIVERSITY U
ON PU.UNI_ID = U.UNI_id;
SELECT * FROM ALL_PROFESSORS

CREATE OR REPLACE VIEW ALL_EVENTS AS
SELECT E.EVT_NAME "EVENT NAME",M.FIRST_NAME AS HOST_NAME,E.EVT_DATETIME"EVENT DATE",E.EVT_LINK"EVENT LINK",ES.EVT_STATUS  "EVENT STATUS" ,EE.SITE_NAME"SITE NAME",EC.CAT_NAME "CATEGORY",U.UNI_NAME "UNIVERSITY NAME",EE.CAPACITY
FROM EVENT E JOIN EVENT_REGISTRATION ER
ON E.EVT_ID =ER.EVT_ID
JOIN EVENT_STATUS ES
ON E.EVT_STATUS =ES.EVT_STATUS_ID
LEFT JOIN EVENT_SITE EE
ON E.EVT_VENUE=EE.SITE_ID
JOIN MEMBERS M
ON E.EVT_HOST_ID =M.MEMBER_ID
JOIN EVENT_CATEGORY EC
ON E.EVT_CAT_ID=EC.CAT_ID
LEFT JOIN UNIVERSITY U
ON U.UNI_ID= EE.UNI_ID;
SELECT * FROM ALL_EVENTS

CREATE OR REPLACE VIEW ALL_PROJECTS AS
SELECT U.UNI_NAME "UNIVERSITY NAME",PROJ_NAME "PROJECT NAME",PROJ_DESC "PROJECT_DESCRIPTION",PROJ_REPO "PROJECT_REPOSITORY",M.FIRST_NAME|| ' ' ||M.LAST_NAME "PROJECT PROFESSOR",PU.EMAIL
FROM OPEN_SOURCE_PROJECTS O 
JOIN UNIVERSITY U
ON O.UNI_ID =U.UNI_ID
JOIN MEMBERS M
ON M.MEMBER_ID=O.PROF_ID
LEFT JOIN PROF_UNIVERSITY PU
ON U.UNI_ID=PU.UNI_ID;
SELECT * FROM ALL_PROJECTS

CREATE OR REPLACE VIEW CHART AS 
SELECT COUNT (U.UNI_ID) AS CONTI,U.UNI_NAME AS UNIVERSITIES,U.UNI_NAME AS UNIV_NAME FROM UNIVERSITY U
JOIN STUDENT S
ON S.UNI_ID=U.UNI_ID
JOIN PROF_UNIVERSITY PU
ON PU.UNI_ID =U.UNI_ID
GROUP BY (U.UNI_NAME);
SELECT * FROM CHART

CREATE OR REPLACE VIEW ALL_ALUMNI AS 
select M.FIRST_NAME|| ' ' || M.LAST_NAME "ALUMNI NAME",EMAIL, POSITION,EXPERIENCE "EXPERIENCE IN YEARS", ALUMNI_BACKGROUND "ALUMNI BACKGROUND"
FROM ALUMNI A
JOIN MEMBERS M
on A.MEMBER_ID= M.MEMBER_ID;
SELECT * FROM ALL_ALUMNI

