SET SERVEROUTPUT ON;

SELECT * FROM MEMBERS;
SELECT * FROM UNIVERSITY;
SELECT * FROM LOCATION;
SELECT * FROM STUDENT;
SELECT * FROM PROFESSOR;
SELECT * FROM ALUMNI;
SELECT * FROM DEPARTMENT;
SELECT * FROM EVENT; --- PUBLIC
SELECT * FROM EVENT_REGISTRATION;
SELECT * FROM EVENT_SITE;
SELECT * FROM OPEN_SOURCE_PROJECT; -- PUBLIC
SELECT * FROM PROF_UNIVERSITY;
SELECT * FROM DEGREE_LEVEL;
SELECT * FROM MEMBER_TYPE;
SELECT * FROM EVENT_CATEGORY;
SELECT * FROM EVENT_STATUS; -- PUBLIC
SELECT * FROM COURSE_MAJOR;



